# Generated by Django 4.0.5 on 2022-06-13 12:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='exercise',
            field=ckeditor.fields.RichTextField(verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='questionentrancetesting',
            name='answers',
            field=models.CharField(max_length=2500, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='questionentrancetesting',
            name='correctAnswer',
            field=models.CharField(max_length=500, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='questionentrancetesting',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questionlessontest',
            name='answers',
            field=models.CharField(max_length=2500, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='questionlessontest',
            name='correctAnswer',
            field=models.CharField(max_length=500, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='questionlessontest',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
