# Generated by Django 4.0.5 on 2022-06-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_courses_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='img',
            field=models.CharField(max_length=1500, null=True, verbose_name='ссылка на изображение'),
        ),
    ]
