# Generated by Django 4.0.5 on 2022-06-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courses_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultlessontest',
            name='course',
            field=models.ForeignKey(db_column='Курс', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='main.courses'),
            preserve_default=False,
        ),
    ]
