# Generated by Django 4.0.5 on 2022-06-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resultlessontest_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultlessontest',
            name='course',
            field=models.ForeignKey(db_column='Курс', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.courses'),
        ),
    ]
