# Generated by Django 4.0.5 on 2022-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(max_length=250, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Имя'),
        ),
    ]
